# Generated by Django 5.0.2 on 2024-05-12 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VL_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebooks',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='ebooks',
            old_name='author_id',
            new_name='autor_id',
        ),
        migrations.RenameField(
            model_name='ebooks',
            old_name='category',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='ebooks',
            old_name='pages',
            new_name='paginas',
        ),
        migrations.RenameField(
            model_name='ebooks',
            old_name='summary',
            new_name='sinopsis',
        ),
        migrations.RenameField(
            model_name='ebooks',
            old_name='title',
            new_name='titulo',
        ),
    ]
