# Generated by Django 5.1.6 on 2025-02-19 19:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VL_app', '0003_multa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialBibliografico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('sinopsis', models.TextField(max_length=2000)),
                ('paginas', models.CharField(max_length=80)),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('autor', models.CharField(max_length=80)),
                ('editorial', models.CharField(max_length=80)),
                ('tipo', models.CharField(choices=[('libro', 'Libro'), ('revista', 'Revista'), ('referencia', 'Referencia')], max_length=20)),
                ('año_publicacion', models.DateField(blank=True, null=True)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('isbn', models.CharField(max_length=13, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrestamoMaterialBibliografico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(auto_now_add=True)),
                ('fecha_devolucion', models.DateField()),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('retirado', 'Retirado'), ('devuelto', 'Devuelto'), ('atrasado', 'Atrasado'), ('no_entregado', 'No entregado')], default='solicitado', max_length=20)),
                ('bibliotecario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_gestionados', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrestamoSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(auto_now_add=True)),
                ('fecha_devolucion', models.DateField()),
                ('nombre_actividad', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('nombre_organizacion', models.CharField(max_length=255)),
                ('numero_contacto', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('nombre_representante', models.CharField(max_length=255)),
                ('ci_representante', models.CharField(max_length=20, unique=True)),
                ('numero_contacto_representante', models.CharField(max_length=15)),
                ('correo_representante', models.EmailField(max_length=254)),
                ('numero_participantes', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SalaTematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tema', models.CharField(max_length=50, unique=True)),
                ('nombre_sala', models.CharField(max_length=255)),
                ('nombre_tema', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='EBooks',
        ),
        migrations.RemoveField(
            model_name='multa',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='multa',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='multa',
            name='responsable',
        ),
        migrations.AddField(
            model_name='multa',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multa',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
