# Generated by Django 5.0.2 on 2025-02-20 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VL_app', '0004_materialbibliografico_prestamomaterialbibliografico_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialbibliografico',
            old_name='año_publicacion',
            new_name='anno_publicacion',
        ),
    ]
