# Generated by Django 5.0.2 on 2025-02-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VL_app', '0005_rename_año_publicacion_materialbibliografico_anno_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamomaterialbibliografico',
            name='libros',
            field=models.ManyToManyField(related_name='prestamos', to='VL_app.materialbibliografico'),
        ),
    ]
